<?php

/**
 * Debug Bar screen template.
 *
 * It uses Silk Icons created by Mark James and released under Creative Commons Attribution 2.5 License.
 *
 * This file is part of the Tracy (http://tracy.nette.org)
 * Copyright (c) 2004 David Grudl (http://davidgrudl.com)
 *
 * @param  array $panels
 * @param  array $info
 * @return void
 */

namespace Tracy;

use Tracy;

?>




<!-- Tracy Debug Bar -->

<style id="tracy-debug-style" class="tracy-debug">
<?php echo preg_replace('#[\r\n\t ]+#', ' ', file_get_contents(__DIR__ . '/bar.css') . file_get_contents(__DIR__ . '/dumper.css')) ?>
</style>

<div id="tracy-debug">
<?php foreach ($panels as $panel): if (!$panel['panel']) continue; ?>
	<div class="tracy-panel" id="tracy-debug-panel-<?php echo $panel['id'] ?>">
		<?php echo $panel['panel'] ?>
		<div class="tracy-icons">
			<a href="#" title="open in window">&curren;</a>
			<a href="#" rel="close" title="close window">&times;</a>
		</div>
	</div>
<?php endforeach ?>

<div id="tracy-debug-bar">
	<ul>
		<li id="tracy-debug-logo" title="<?php echo htmlSpecialChars(implode(" |\n", $info), ENT_QUOTES, 'UTF-8')?>">&nbsp;<span>Tracy</span></li>
		<?php foreach ($panels as $panel): if (!$panel['tab']) continue; ?>
		<?php if (!empty($panel['previous'])) echo '</ul><ul class="tracy-previous">'; ?>
		<li><?php if ($panel['panel']): ?><a href="#" rel="<?php echo $panel['id'] ?>"><?php echo trim($panel['tab']) ?></a><?php else: echo '<span>', trim($panel['tab']), '</span>'; endif ?></li>
		<?php endforeach ?>
		<li><a href="#" rel="close" title="close debug bar">&times;</a></li>
	</ul>
</div>
</div>

<script id="tracy-debug-script">
(function() {
	if (!document.documentElement.classList) {
		document.write('<div style="position:fixed;right:0;bottom:0;z-index:30000;font:normal normal 12px/21px sans-serif;color:#333;background:#EDEAE0;border:1px solid #ccc;padding:.2em">Warning: Tracy requires IE 10+<\/div>');
		return;
	}

	<?php echo preg_replace(array('#//.*#', '#[\r\n\t ]+#'), ' ', file_get_contents(__DIR__ . '/bar.js') . file_get_contents(__DIR__ . '/dumper.js')) ?>

	Tracy.Dumper.init(<?php echo json_encode(Dumper::fetchLiveData()) ?>);
	Tracy.Debug.init();
})();
</script>

<!-- /Tracy Debug Bar -->
